// src/pages/Parsers.tsx
import { useState } from "preact/hooks";
import { Banner } from "../components/Banner";
import { ParseTree } from "../components/ParseTree";

export const Parsers = () => {
  const [code, setCode] = useState("1 + 2 * 3 + 4");
  const [highlight, setHighlight] = useState<[number, number] | null>(null);

  return (
    <>
      <Banner title="Parsers" />
      <div class="content">
        <div
          style={{
            flex: "1",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <div>
            {highlight && (
              <div class="highlight">
                <span
                  class="spacer"
                  dangerouslySetInnerHTML={{
                    __html: "&nbsp;".repeat(highlight[0]),
                  }}
                />
                <span
                  class="underline"
                  dangerouslySetInnerHTML={{
                    __html: "&nbsp;".repeat(highlight[1] - highlight[0]),
                  }}
                />
              </div>
            )}
            <input
              type="text"
              class="code-input"
              data-gramm="false"
              data-gramm_editor="false"
              data-enable-grammarly="false"
              data-lt-active="false"
              value={code}
              onKeyUp={(e) => setCode((e.target as HTMLTextAreaElement).value)}
              onChange={(e) => setCode((e.target as HTMLTextAreaElement).value)}
            />
          </div>
          <p style={{ maxWidth: "400px" }}>
            This is a simple recursive descent parser, that builds a parse tree
            for a mathmatical expression. Each operation is represented as a
            node with two children, and each value in the expression is a leaf
            node in the tree.
          </p>
        </div>
        <div style={{ flex: "1" }}>
          <ParseTree code={code} setHighlight={setHighlight} />
        </div>
      </div>
    </>
  );
};

// src/routes/parsers/+page.svelte
<script>
  import Banner from "$lib/banner.svelte";

  let code = $state("");
  let highlight = $state([2, 4]);
</script>

<main>
  <Banner>Parsers</Banner>
  <div class="mx-auto flex w-full max-w-4xl flex-row place-content-center">
    <div class="flex-1 flex flex-col gap-4">
      {#if highlight}
        <div class="highlight">
          <span class="highlight-spacer">
            {"\u00a0".repeat(highlight[0])}
          </span>
          <span class="highlight-underline">
            {"\u00a0".repeat(highlight[1] - highlight[0])}
          </span>
        </div>
      {/if}
      <input value={code} oninput={(e) => (code = e.target.value)} />
      <p class="max-w-[400px]">
        This is a simple recursive descent parser, that builds a parse tree for
        a mathmatical expression. Each operation is represented as a node with
        two children, and each value in the expression is a leaf node in the
        tree.
      </p>
    </div>
    <div class="flex-1">Tree</div>
  </div>
</main>

<style>
  input {
    font-family: "Martian Mono", monospace;
    font-size: 32px;
    width: 400px;

    padding: 4px 8px;
    border: 3px solid var(--light-gray);
    border-radius: 10px;

    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
  }

  input:focus {
    outline: none;
    border-color: var(--blue);
  }

  .highlight {
    color: var(--green);
    position: absolute;
    width: 400px;
    padding: 5px 11px;
    margin-top: -2px;

    display: flex;
    pointer-events: none;
  }

  .highlight > span {
    font-family: "Martian Mono", monospace;
    font-size: 32px;
  }

  .highlight-underline {
    position: relative;
  }

  .highlight-underline::after {
    box-sizing: border-box;
    content: "";
    position: absolute;
    width: 100%;
    border: 2px solid var(--green);
    background-color: var(--green);
    border-radius: 5px;
    bottom: -5px;
    left: 0px;

    animation: slide-in 200ms 1;
  }

  @keyframes slide-in {
    0% {
      width: 0;
    }
    100% {
      width: 100%;
    }
  }
</style>
